query GetAllNightStay($startPrice: Float, $endPrice: Float) {
  getAllNightStay(startPrice: $startPrice, endPrice: $endPrice) {
    total
    data {
      name
      images
      price
      id
    }
  }
}