query GetPackageById($getPackageByIdId: ID!) {
  getPackageById(id: $getPackageByIdId) {
    id
    category_id
    images
    day
    night
    name
    title
    description
    price
    createdAt
    updatedAt
    Category {
      id
      name
    }
    Highlights {
      id
      name
    }
    Includes {
      id
      name
      image
    }
    Inclusions {
      id
      title
    }
    Exclusions {
      id
      title
    }
    Itinerary {
      id
      name
      title
      description
    }
    Faqs {
      id
      title
      description
    }
  }
}
